# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      result:
        description: 'Result'
        default: 0
        required: true

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: set-step
        id: step1
        run: echo "::set-output name=test::${{ github.event.inputs.result }}"
      - name: out-step
        run: |
          echo RESULT: ${{ steps.step1.outputs.test }}
      - name: after-step
        if: steps.step1.outputs.test == 0
        run: |
          echo RUN AFTER STEP
